
GC Util
110.22445729979256
136908
266.0
0.0
120.0
95.68986116324439
1.0881836421730766
0.27651583084476467
heapSize
99.9912356940965
136919
100
0
100.0
0.9361411100175916
numThreads
99.9912356940965
136919
100
0
100.0
0.9361411100175916
GCInterval
0.0
136919
0
0
0.0
0.0
Correlation
                Time   GC Util  heapSize  numThreads  GCInterval
Time        1.000000  0.128263  0.014043    0.014043         NaN
GC Util     0.128263  1.000000  0.003113    0.003113         NaN
heapSize    0.014043  0.003113  1.000000    1.000000         NaN
numThreads  0.014043  0.003113  1.000000    1.000000         NaN
GCInterval       NaN       NaN       NaN         NaN         NaN
R Means Squared
Traceback (most recent call last):
  File "code/summary-stats/calcSummStats.py", line 55, in <module>
    print(sqrt(mean_squared_error(jdk['GC Util'], gc_util_true)))
  File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/regression.py", line 241, in mean_squared_error
    y_true, y_pred, multioutput)
  File "/usr/local/lib/python3.7/site-packages/sklearn/metrics/regression.py", line 78, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False)
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
